title: Sambit's Blog
description: When you cannot go back, you have to worry only about the best way of moving forward.
show_downloads: false

baseurl: "/sambit-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://sambit-giri.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: sambit-giri
image: /thumbnail-jumbo.png
twitter:
  username: sam_giri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
